services:
  - type: web
    name: sahajyog
    runtime: docker
    plan: starter
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sahajyog-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        sync: false
      - key: POOL_SIZE
        value: 10
      - key: PHX_SERVER
        value: true
      - key: GOOGLE_PLACES_API_KEY
        sync: false
    healthCheckPath: /

databases:
  - name: sahajyog-db
    databaseName: sahajyog
    plan: free
    region: oregon
